### Numpy->Play with arrays(numbers)
### pandas->Dataset
### Matplotlib-> data visualization
### Scipy->Statistical
### Skylearn->Algorithm

In [1]:
import numpy as np

In [7]:
list1=[2,3,4]
np.array(list1)

array([2, 3, 4])

In [3]:
np.array(list1)

array([2, 3, 4])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
listn=[[1,2,3],[4,5,6],[7,8,9]]
np.array(listn)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [12]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [13]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [22]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [23]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [24]:
np.random.rand(3,5)

array([[0.97335711, 0.47004007, 0.80925832, 0.86003763, 0.96164149],
       [0.20025574, 0.30082476, 0.04100683, 0.51650624, 0.92731419],
       [0.85324052, 0.35049302, 0.64879286, 0.91739437, 0.50018005]])

In [25]:
arr=np.random.randn(2,4)
arr

array([[ 2.3584915 ,  1.73041996, -1.25789166,  0.67553963],
       [-0.12766275, -1.27653221,  1.5190381 ,  0.0549487 ]])

In [26]:
np.random.randint(1,100)

86

In [27]:
np.random.randint(20,56,100)

array([55, 30, 26, 30, 37, 27, 52, 54, 36, 36, 49, 54, 23, 34, 45, 25, 20,
       30, 29, 39, 45, 31, 48, 49, 51, 46, 39, 40, 27, 33, 24, 48, 54, 52,
       29, 39, 26, 52, 44, 34, 31, 36, 34, 29, 40, 47, 28, 24, 51, 42, 54,
       43, 47, 43, 31, 30, 44, 28, 29, 23, 33, 48, 24, 44, 37, 44, 30, 50,
       24, 46, 43, 29, 31, 50, 30, 29, 22, 39, 42, 37, 44, 31, 26, 48, 41,
       29, 27, 27, 20, 23, 22, 51, 21, 30, 28, 51, 20, 48, 29, 40])

In [29]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
rand_array.max()

NameError: name 'rand_array' is not defined

In [32]:
sample_array.max()

29

In [33]:
sample_array.argmax()

29

In [34]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a=np.random.rand(2,3)

In [37]:
a

array([[0.63351378, 0.1794938 , 0.95420919],
       [0.53073094, 0.31885245, 0.72716821]])

In [38]:
a.T

array([[0.63351378, 0.53073094],
       [0.1794938 , 0.31885245],
       [0.95420919, 0.72716821]])

In [40]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
sample_array[0]

10

In [42]:
sample_array[2:5]

array([12, 13, 14])

In [43]:
sample_array[1:4]=300

In [44]:
sample_array

array([ 10, 300, 300, 300,  14,  15,  16,  17,  18,  19,  20])

In [45]:
sample_array[0:7]

array([ 10, 300, 300, 300,  14,  15,  16])

In [46]:
sample_array1=sample_array[0:7]
sample_array1

array([ 10, 300, 300, 300,  14,  15,  16])

In [47]:
sample_array1[:]
sample_array

array([ 10, 300, 300, 300,  14,  15,  16,  17,  18,  19,  20])

In [48]:
sample_array1[:]=100

In [49]:
sample_array1

array([100, 100, 100, 100, 100, 100, 100])